import type {
  AdminApplicantStakeholder,
  AdminApplication,
  AdminCertificate,
  AdminFieldInspection,
  AdminGatcOfficerStakeholder,
  AdminInstrument,
  AdminLmoOfficerStakeholder,
  AdminOfficer,
} from './adminTypes'

export const initialAdminOfficers: AdminOfficer[] = [
  { id: 'LMO-DEL-042', name: 'L. Mehta (LMO)', email: 'l.mehta@measuresure.gov.in', role: 'Legal Metrology Officer', district: 'South Delhi', activeCases: 4, phone: '+91 98109 87654' },
  { id: 'LMO-DEL-019', name: 'R. Iyer (LMO)', email: 'r.iyer@measuresure.gov.in', role: 'Legal Metrology Officer', district: 'North Delhi', activeCases: 3, phone: '+91 98712 34567' },
  { id: 'LMO-DEL-088', name: 'S. K. Verma (LMO)', email: 'sk.verma@measuresure.gov.in', role: 'Legal Metrology Officer', district: 'North West Delhi', activeCases: 5, phone: '+91 97111 22334' },
  { id: 'LMO-DEL-055', name: 'P. Sharma (LMO)', email: 'p.sharma@measuresure.gov.in', role: 'Legal Metrology Officer', district: 'Central Delhi', activeCases: 2, phone: '+91 99100 88776' },
  { id: 'LMO-DEL-102', name: 'A. K. Rai (LMO)', email: 'ak.rai@measuresure.gov.in', role: 'Legal Metrology Officer', district: 'South West Delhi', activeCases: 3, phone: '+91 98115 55443' },
]

export const initialAdminApplications: AdminApplication[] = [
  {
    id: 'LM-2024-08421',
    type: 'Re-verification',
    instrumentId: 'WM-DEL-01982',
    instrument: 'Heavy Weighbridge 60T',
    applicant: 'Metro Cash & Carry India Pvt Ltd',
    applicantGstin: '07AAACM4821K1Z5',
    applicantEmail: 'compliance@metrocash.in',
    applicantPhone: '+91 99100 11223',
    applicantAddress: 'Plot 12, Okhla Industrial Area Phase II, South Delhi 110020',
    location: 'Okhla Phase II',
    district: 'South Delhi',
    submitted: 'Today, 09:42 AM',
    submittedDate: '2024-09-25',
    assignedOfficer: 'L. Mehta (LMO)',
    assignedOfficerEmail: 'l.mehta@measuresure.gov.in',
    status: 'Pending Review',
    documents: [
      { id: 'doc-1', name: 'Previous Verification Certificate.pdf', type: 'PDF', size: '1.2 MB', uploadedDate: '24 Sep 2024' },
      { id: 'doc-2', name: 'Manufacturer Calibration Test Sheet.pdf', type: 'PDF', size: '2.4 MB', uploadedDate: '24 Sep 2024' },
      { id: 'doc-3', name: 'Premises GST Registration.pdf', type: 'PDF', size: '850 KB', uploadedDate: '24 Sep 2024' },
    ],
    remarks: [
      { id: 'rem-1', author: 'Arun Verma (Applicant)', role: 'Applicant', date: '25 Sep 2024, 09:42 AM', text: 'Submitted annual re-verification request for Okhla weighbridge unit #1.' },
    ],
    history: [
      { id: 'hist-1', date: '25 Sep 2024, 09:42 AM', action: 'Application Submitted', by: 'Metro Cash & Carry', notes: 'Fee paid via BharatKosh PG-99821' },
      { id: 'hist-2', date: '25 Sep 2024, 10:15 AM', action: 'Assigned to LMO', by: 'System Router', notes: 'Auto-routed to South Delhi cluster' },
    ],
  },
  {
    id: 'LM-2024-08420',
    type: 'Initial verification',
    instrumentId: 'WM-DEL-01981',
    instrument: 'Platform Scale 500kg',
    applicant: 'Anand Wholesale Traders',
    applicantGstin: '07ABAPW9918J1Z2',
    applicantEmail: 'anand.wholesales@gmail.com',
    applicantPhone: '+91 98112 33445',
    applicantAddress: 'Shop 44, Azadpur Wholesale Fruit Mandi, North Delhi 110033',
    location: 'Azadpur Mandi',
    district: 'North Delhi',
    submitted: 'Yesterday, 04:15 PM',
    submittedDate: '2024-09-24',
    assignedOfficer: 'R. Iyer (LMO)',
    assignedOfficerEmail: 'r.iyer@measuresure.gov.in',
    status: 'Under Review',
    documents: [
      { id: 'doc-10', name: 'Purchase Invoice & Model Approval.pdf', type: 'PDF', size: '1.8 MB', uploadedDate: '24 Sep 2024' },
      { id: 'doc-11', name: 'Repairer Stamping Declaration.pdf', type: 'PDF', size: '1.1 MB', uploadedDate: '24 Sep 2024' },
    ],
    remarks: [
      { id: 'rem-10', author: 'R. Iyer (LMO)', role: 'Legal Metrology Officer', date: '24 Sep 2024, 05:00 PM', text: 'Documents initial check complete. Physical inspection site visit required.' },
    ],
    history: [
      { id: 'hist-10', date: '24 Sep 2024, 04:15 PM', action: 'Application Submitted', by: 'Anand Wholesale Traders' },
      { id: 'hist-11', date: '24 Sep 2024, 05:00 PM', action: 'Under Review', by: 'R. Iyer (LMO)', notes: 'Verified model approval certificate.' },
    ],
  },
  {
    id: 'LM-2024-08419',
    type: 'Re-verification',
    instrumentId: 'WM-DEL-01976',
    instrument: 'Fuel Dispenser Unit 4-Hose',
    applicant: 'Bharat Petroleum Outlet Narela',
    applicantGstin: '07AAACB0012P1Z9',
    applicantEmail: 'narela.retail@bpcl.in',
    applicantPhone: '+91 97111 88990',
    applicantAddress: 'NH-44 Narela Junction, North West Delhi 110040',
    location: 'Narela',
    district: 'North West Delhi',
    submitted: '18 Sep 2024',
    submittedDate: '2024-09-18',
    assignedOfficer: 'S. K. Verma (LMO)',
    assignedOfficerEmail: 'sk.verma@measuresure.gov.in',
    status: 'Approved',
    documents: [
      { id: 'doc-20', name: 'GATC Test Clearance Report.pdf', type: 'PDF', size: '3.1 MB', uploadedDate: '19 Sep 2024' },
      { id: 'doc-21', name: 'Lead Seal Certificate.pdf', type: 'PDF', size: '920 KB', uploadedDate: '20 Sep 2024' },
    ],
    remarks: [
      { id: 'rem-20', author: 'State Administrator', role: 'State Admin', date: '21 Sep 2024, 11:30 AM', text: 'Approved based on clean GATC lab report & LMO physical endorsement.' },
    ],
    history: [
      { id: 'hist-20', date: '18 Sep 2024', action: 'Application Submitted', by: 'Bharat Petroleum' },
      { id: 'hist-21', date: '20 Sep 2024', action: 'Inspection Passed', by: 'S. K. Verma (LMO)' },
      { id: 'hist-22', date: '21 Sep 2024', action: 'Final Approval', by: 'State Administrator' },
    ],
  },
  {
    id: 'LM-2024-08418',
    type: 'After repair',
    instrumentId: 'WM-DEL-01974',
    instrument: 'Counter Scale 15kg Class III',
    applicant: 'Sharma Grocers & Provision Store',
    applicantGstin: '07ACDPS4412A1Z3',
    applicantEmail: 'sharmagrocer@gmail.com',
    applicantPhone: '+91 99100 44332',
    applicantAddress: 'Central Market Lajpat Nagar II, South Delhi 110024',
    location: 'Lajpat Nagar',
    district: 'South Delhi',
    submitted: '18 Sep 2024',
    submittedDate: '2024-09-18',
    assignedOfficer: 'P. Sharma (LMO)',
    assignedOfficerEmail: 'p.sharma@measuresure.gov.in',
    status: 'Returned for Correction',
    documents: [
      { id: 'doc-30', name: 'Repairer Invoice.pdf', type: 'PDF', size: '540 KB', uploadedDate: '18 Sep 2024' },
    ],
    remarks: [
      { id: 'rem-30', author: 'P. Sharma (LMO)', role: 'LMO', date: '19 Sep 2024', text: 'Repairer license certificate copy is missing from application bundle.' },
      { id: 'rem-31', author: 'State Admin', role: 'State Admin', date: '20 Sep 2024', text: 'Returned to applicant to attach authorized repairer license copy.' },
    ],
    history: [
      { id: 'hist-30', date: '18 Sep 2024', action: 'Submitted', by: 'Sharma Grocers' },
      { id: 'hist-31', date: '20 Sep 2024', action: 'Returned for Correction', by: 'State Administrator', notes: 'Missing repairer authorization' },
    ],
  },
  {
    id: 'LM-2024-08417',
    type: 'Special inspection',
    instrumentId: 'WM-DEL-01955',
    instrument: 'Storage Tank Gauging System',
    applicant: 'Indian Oil Depot Bijwasan',
    applicantGstin: '07AAACI0011R1Z8',
    applicantEmail: 'bijwasan.depot@indianoil.in',
    applicantPhone: '+91 98111 22110',
    applicantAddress: 'IOCL Terminal Bijwasan, South West Delhi 110061',
    location: 'Bijwasan',
    district: 'South West Delhi',
    submitted: '15 Sep 2024',
    submittedDate: '2024-09-15',
    assignedOfficer: 'A. K. Rai (LMO)',
    assignedOfficerEmail: 'ak.rai@measuresure.gov.in',
    status: 'Assigned',
    documents: [
      { id: 'doc-40', name: 'Tank Calibration Table 2024.pdf', type: 'PDF', size: '4.5 MB', uploadedDate: '15 Sep 2024' },
    ],
    remarks: [
      { id: 'rem-40', author: 'State Admin', role: 'State Admin', date: '16 Sep 2024', text: 'Assigned to Officer A. K. Rai for joint inspection with CPCB team.' },
    ],
    history: [
      { id: 'hist-40', date: '15 Sep 2024', action: 'Application Submitted', by: 'Indian Oil Depot' },
      { id: 'hist-41', date: '16 Sep 2024', action: 'Assigned Officer', by: 'State Administrator', notes: 'Assigned A. K. Rai (LMO)' },
    ],
  },
]

export const initialAdminInstruments: AdminInstrument[] = [
  {
    id: 'WM-DEL-01982',
    type: 'Heavy Weighbridge 60T',
    manufacturer: 'Mettler Toledo',
    model: 'IND570 Weighbridge',
    serialNumber: 'AD2401982',
    capacity: '60,000 kg x 10 kg',
    accuracyClass: 'Class IV Commercial',
    location: 'Okhla Industrial Area Phase II',
    district: 'South Delhi',
    owner: 'Metro Cash & Carry India Pvt Ltd',
    ownerGstin: '07AAACM4821K1Z5',
    ownerContact: '+91 99100 11223',
    ownerEmail: 'compliance@metrocash.in',
    status: 'Pending Verification',
    lastVerification: '24 Sep 2023',
    nextDue: '24 Sep 2024',
    assignedLmo: 'L. Mehta (LMO)',
    certificateNo: 'LM-CERT-2023-9982',
    isFlagged: false,
    markedForInspection: false,
    verificationHistory: [
      { id: 'vh-1', certNo: 'LM-CERT-2023-9982', issuedDate: '24 Sep 2023', expiryDate: '24 Sep 2024', outcome: 'Passed', lmo: 'L. Mehta (LMO)', remarks: 'Annual verification completed with standard 20T test truck.' },
      { id: 'vh-2', certNo: 'LM-CERT-2022-8112', issuedDate: '22 Sep 2022', expiryDate: '22 Sep 2023', outcome: 'Passed', lmo: 'L. Mehta (LMO)' },
    ],
  },
  {
    id: 'WM-DEL-01981',
    type: 'Platform Scale 500kg',
    manufacturer: 'Essae-Teraoka',
    model: 'PB-500 Heavy Duty',
    serialNumber: 'ES2401981',
    capacity: '500 kg x 100g',
    accuracyClass: 'Class III Medium',
    location: 'Azadpur Wholesale Fruit Mandi',
    district: 'North Delhi',
    owner: 'Anand Wholesale Traders',
    ownerGstin: '07ABAPW9918J1Z2',
    ownerContact: '+91 98112 33445',
    ownerEmail: 'anand.wholesales@gmail.com',
    status: 'Expiring Soon',
    lastVerification: '25 Sep 2023',
    nextDue: '25 Sep 2024',
    assignedLmo: 'R. Iyer (LMO)',
    certificateNo: 'LM-CERT-2023-8812',
    isFlagged: false,
    markedForInspection: true,
    inspectionNotes: 'Marked for surprise seasonal mandi check by State Admin',
    verificationHistory: [
      { id: 'vh-10', certNo: 'LM-CERT-2023-8812', issuedDate: '25 Sep 2023', expiryDate: '25 Sep 2024', outcome: 'Passed', lmo: 'R. Iyer (LMO)' },
    ],
  },
  {
    id: 'WM-DEL-01976',
    type: 'Fuel Dispenser Unit 4-Hose',
    manufacturer: 'Gilbarco Veeder-Root',
    model: 'Encore 700 S',
    serialNumber: 'GB2401976',
    capacity: '50 L/min per nozzle',
    accuracyClass: 'Class 0.5 High Accuracy',
    location: 'NH-44 Narela Junction',
    district: 'North West Delhi',
    owner: 'Bharat Petroleum Outlet Narela',
    ownerGstin: '07AAACB0012P1Z9',
    ownerContact: '+91 97111 88990',
    ownerEmail: 'narela.retail@bpcl.in',
    status: 'Active',
    lastVerification: '18 Sep 2024',
    nextDue: '18 Sep 2025',
    assignedLmo: 'S. K. Verma (LMO)',
    certificateNo: 'LM-CERT-2024-9176',
    isFlagged: false,
    markedForInspection: false,
    verificationHistory: [
      { id: 'vh-20', certNo: 'LM-CERT-2024-9176', issuedDate: '18 Sep 2024', expiryDate: '18 Sep 2025', outcome: 'Passed', lmo: 'S. K. Verma (LMO)', remarks: 'Calibrated with 5L and 10L standard proving cans.' },
    ],
  },
  {
    id: 'WM-DEL-01974',
    type: 'Retail Counter Scale 15kg',
    manufacturer: 'Mettler Toledo',
    model: 'bPlus Counter',
    serialNumber: 'MT2401974',
    capacity: '15 kg x 5g',
    accuracyClass: 'Class III',
    location: 'Central Market Lajpat Nagar II',
    district: 'South Delhi',
    owner: 'Sharma Grocers & Provision Store',
    ownerGstin: '07ACDPS4412A1Z3',
    ownerContact: '+91 99100 44332',
    ownerEmail: 'sharmagrocer@gmail.com',
    status: 'Expired',
    lastVerification: '10 Aug 2023',
    nextDue: '10 Aug 2024',
    assignedLmo: 'P. Sharma (LMO)',
    certificateNo: 'LM-CERT-2023-6611',
    isFlagged: true,
    flagReason: 'Consumer complaint received regarding weight discrepancy on packaged items.',
    markedForInspection: true,
    inspectionNotes: 'Enforcement inspection recommended',
    verificationHistory: [
      { id: 'vh-30', certNo: 'LM-CERT-2023-6611', issuedDate: '10 Aug 2023', expiryDate: '10 Aug 2024', outcome: 'Passed', lmo: 'P. Sharma (LMO)' },
    ],
  },
  {
    id: 'WM-DEL-01955',
    type: 'Storage Tank Gauging System',
    manufacturer: 'Endress+Hauser',
    model: 'Tankvision Pro',
    serialNumber: 'EH2401955',
    capacity: '50,000 Kilolitres',
    accuracyClass: 'Class 0.2',
    location: 'IOCL Terminal Bijwasan',
    district: 'South West Delhi',
    owner: 'Indian Oil Depot Bijwasan',
    ownerGstin: '07AAACI0011R1Z8',
    ownerContact: '+91 98111 22110',
    ownerEmail: 'bijwasan.depot@indianoil.in',
    status: 'Active',
    lastVerification: '12 Jul 2024',
    nextDue: '12 Jul 2025',
    assignedLmo: 'A. K. Rai (LMO)',
    certificateNo: 'LM-CERT-2024-5544',
    isFlagged: false,
    markedForInspection: false,
    verificationHistory: [
      { id: 'vh-40', certNo: 'LM-CERT-2024-5544', issuedDate: '12 Jul 2024', expiryDate: '12 Jul 2025', outcome: 'Passed', lmo: 'A. K. Rai (LMO)' },
    ],
  },
]

/* --- INITIAL CERTIFICATES DATA --- */

export const initialAdminCertificates: AdminCertificate[] = [
  {
    id: 'CERT-DEL-9982',
    certNo: 'LM-CERT-2024-9982',
    instrumentId: 'WM-DEL-01982',
    instrumentType: 'Heavy Weighbridge 60T',
    applicant: 'Metro Cash & Carry India Pvt Ltd',
    location: 'Okhla Industrial Area Phase II',
    district: 'South Delhi',
    issuedDate: '24 Sep 2024',
    expiryDate: '24 Sep 2025',
    issuedBy: 'L. Mehta (LMO)',
    status: 'Active',
    isVerified: true,
    isFlagged: false,
    sealNo: 'LM-SEAL-S9982',
    accuracyClass: 'Class IV Commercial',
    history: [
      { id: 'ch-1', date: '24 Sep 2024, 02:30 PM', action: 'Certificate Issued & Stamped', by: 'L. Mehta (LMO)' },
      { id: 'ch-2', date: '24 Sep 2024, 03:00 PM', action: 'Logged into State Register', by: 'System' },
    ],
  },
  {
    id: 'CERT-DEL-9176',
    certNo: 'LM-CERT-2024-9176',
    instrumentId: 'WM-DEL-01976',
    instrumentType: 'Fuel Dispenser Unit 4-Hose',
    applicant: 'Bharat Petroleum Outlet Narela',
    location: 'NH-44 Narela Junction',
    district: 'North West Delhi',
    issuedDate: '18 Sep 2024',
    expiryDate: '18 Sep 2025',
    issuedBy: 'S. K. Verma (LMO)',
    status: 'Active',
    isVerified: true,
    isFlagged: false,
    sealNo: 'LM-SEAL-NW9176',
    accuracyClass: 'Class 0.5 High Accuracy',
    history: [
      { id: 'ch-10', date: '18 Sep 2024', action: 'Certificate Issued', by: 'S. K. Verma (LMO)' },
    ],
  },
  {
    id: 'CERT-DEL-8812',
    certNo: 'LM-CERT-2023-8812',
    instrumentId: 'WM-DEL-01981',
    instrumentType: 'Platform Scale 500kg',
    applicant: 'Anand Wholesale Traders',
    location: 'Azadpur Wholesale Fruit Mandi',
    district: 'North Delhi',
    issuedDate: '25 Sep 2023',
    expiryDate: '25 Sep 2024',
    issuedBy: 'R. Iyer (LMO)',
    status: 'Expiring Soon',
    isVerified: true,
    isFlagged: false,
    sealNo: 'LM-SEAL-N8812',
    accuracyClass: 'Class III Medium',
    history: [
      { id: 'ch-20', date: '25 Sep 2023', action: 'Certificate Issued', by: 'R. Iyer (LMO)' },
    ],
  },
  {
    id: 'CERT-DEL-6611',
    certNo: 'LM-CERT-2023-6611',
    instrumentId: 'WM-DEL-01974',
    instrumentType: 'Retail Counter Scale 15kg',
    applicant: 'Sharma Grocers & Provision Store',
    location: 'Central Market Lajpat Nagar II',
    district: 'South Delhi',
    issuedDate: '10 Aug 2023',
    expiryDate: '10 Aug 2024',
    issuedBy: 'P. Sharma (LMO)',
    status: 'Expired',
    isVerified: false,
    isFlagged: true,
    flagReason: 'Consumer weight complaint received',
    sealNo: 'LM-SEAL-S6611',
    accuracyClass: 'Class III',
    history: [
      { id: 'ch-30', date: '10 Aug 2023', action: 'Certificate Issued', by: 'P. Sharma (LMO)' },
      { id: 'ch-31', date: '11 Aug 2024', action: 'Certificate Expired', by: 'System' },
    ],
  },
  {
    id: 'CERT-DEL-5544',
    certNo: 'LM-CERT-2024-5544',
    instrumentId: 'WM-DEL-01955',
    instrumentType: 'Storage Tank Gauging System',
    applicant: 'Indian Oil Depot Bijwasan',
    location: 'IOCL Terminal Bijwasan',
    district: 'South West Delhi',
    issuedDate: '12 Jul 2024',
    expiryDate: '12 Jul 2025',
    issuedBy: 'A. K. Rai (LMO)',
    status: 'Active',
    isVerified: true,
    isFlagged: false,
    sealNo: 'LM-SEAL-SW5544',
    accuracyClass: 'Class 0.2',
    history: [
      { id: 'ch-40', date: '12 Jul 2024', action: 'Certificate Issued', by: 'A. K. Rai (LMO)' },
    ],
  },
]

/* --- INITIAL FIELD OPERATIONS DATA --- */

export const initialAdminInspections: AdminFieldInspection[] = [
  {
    id: 'INSP-2024-101',
    instrumentId: 'WM-DEL-01982',
    instrument: 'Heavy Weighbridge 60T',
    applicant: 'Metro Cash & Carry India Pvt Ltd',
    lmoOfficer: 'L. Mehta (LMO)',
    lmoEmail: 'l.mehta@measuresure.gov.in',
    scheduledDate: '2024-09-25',
    scheduledTime: '10:00 AM',
    location: 'Okhla Industrial Area Phase II',
    district: 'South Delhi',
    inspectionType: 'Re-verification',
    status: 'Completed',
    reportSummary: {
      decision: 'PASSED',
      notes: 'All 4 corner load cells passed test load within 5kg tolerance.',
      readings: [
        { loadKg: 10000, errorKg: 2, passed: true },
        { loadKg: 30000, errorKg: 4, passed: true },
        { loadKg: 60000, errorKg: 5, passed: true },
      ],
      photosCaptured: 4,
      sealVerified: true,
    },
    history: [
      { id: 'ih-1', date: '25 Sep 2024, 10:00 AM', action: 'Field Inspection Started', by: 'L. Mehta (LMO)' },
      { id: 'ih-2', date: '25 Sep 2024, 11:30 AM', action: 'Inspection Report Submitted', by: 'L. Mehta (LMO)' },
    ],
  },
  {
    id: 'INSP-2024-102',
    instrumentId: 'WM-DEL-01981',
    instrument: 'Platform Scale 500kg',
    applicant: 'Anand Wholesale Traders',
    lmoOfficer: 'R. Iyer (LMO)',
    lmoEmail: 'r.iyer@measuresure.gov.in',
    scheduledDate: '2024-09-25',
    scheduledTime: '11:30 AM',
    location: 'Azadpur Wholesale Fruit Mandi',
    district: 'North Delhi',
    inspectionType: 'Initial verification',
    status: 'In Progress',
    reportSummary: {
      decision: 'PASSED',
      notes: 'Ongoing Mandi verification drive.',
      readings: [
        { loadKg: 100, errorKg: 0.05, passed: true },
        { loadKg: 500, errorKg: 0.1, passed: true },
      ],
      photosCaptured: 2,
      sealVerified: true,
    },
    history: [
      { id: 'ih-10', date: '25 Sep 2024, 11:30 AM', action: 'Officer arrived at Mandi', by: 'R. Iyer (LMO)' },
    ],
  },
  {
    id: 'INSP-2024-103',
    instrumentId: 'WM-DEL-01976',
    instrument: 'Fuel Dispenser Unit 4-Hose',
    applicant: 'Bharat Petroleum Outlet Narela',
    lmoOfficer: 'S. K. Verma (LMO)',
    lmoEmail: 'sk.verma@measuresure.gov.in',
    scheduledDate: '2024-09-26',
    scheduledTime: '09:00 AM',
    location: 'NH-44 Narela Junction',
    district: 'North West Delhi',
    inspectionType: 'Re-verification',
    status: 'Scheduled',
    history: [
      { id: 'ih-20', date: '24 Sep 2024', action: 'Inspection Scheduled', by: 'State Admin' },
    ],
  },
  {
    id: 'INSP-2024-104',
    instrumentId: 'WM-DEL-01974',
    instrument: 'Counter Scale 15kg',
    applicant: 'Sharma Grocers & Provision Store',
    lmoOfficer: 'P. Sharma (LMO)',
    lmoEmail: 'p.sharma@measuresure.gov.in',
    scheduledDate: '2024-09-24',
    scheduledTime: '02:00 PM',
    location: 'Central Market Lajpat Nagar II',
    district: 'South Delhi',
    inspectionType: 'Enforcement Raid',
    status: 'Pending Review',
    isFlagged: true,
    flagReason: 'Consumer weight complaint pending administrative clearance',
    reportSummary: {
      decision: 'FLAGGED',
      notes: 'Counter scale showed +45g positive error at 10kg load.',
      readings: [
        { loadKg: 5, errorKg: 0.02, passed: true },
        { loadKg: 10, errorKg: 0.045, passed: false },
      ],
      photosCaptured: 3,
      sealVerified: false,
    },
    history: [
      { id: 'ih-30', date: '24 Sep 2024, 02:00 PM', action: 'Enforcement Raid Conducted', by: 'P. Sharma (LMO)' },
      { id: 'ih-31', date: '24 Sep 2024, 03:30 PM', action: 'Report Submitted for Admin Review', by: 'P. Sharma (LMO)' },
    ],
  },
]

/* --- INITIAL STAKEHOLDERS DATA --- */

export const initialApplicants: AdminApplicantStakeholder[] = [
  { id: 'APP-01', name: 'Metro Cash & Carry India Pvt Ltd', organization: 'Commercial Supermarket Chain', gstin: '07AAACM4821K1Z5', contactPerson: 'Arun Verma', email: 'compliance@metrocash.in', phone: '+91 99100 11223', location: 'Okhla Phase II', district: 'South Delhi', totalApplications: 14, totalInstruments: 45, status: 'Active' },
  { id: 'APP-02', name: 'Anand Wholesale Traders', organization: 'Wholesale Mandi Merchant', gstin: '07ABAPW9918J1Z2', contactPerson: 'Anand Kumar', email: 'anand.wholesales@gmail.com', phone: '+91 98112 33445', location: 'Azadpur Mandi', district: 'North Delhi', totalApplications: 8, totalInstruments: 12, status: 'Active' },
  { id: 'APP-03', name: 'Bharat Petroleum Narela Outlet', organization: 'Fuel Retailer', gstin: '07AAACB0012P1Z9', contactPerson: 'Ramanathan V.', email: 'narela.retail@bpcl.in', phone: '+91 97111 88990', location: 'Narela Junction', district: 'North West Delhi', totalApplications: 19, totalInstruments: 8, status: 'Active' },
  { id: 'APP-04', name: 'Sharma Grocers & Provision Store', organization: 'Retail Grocery Store', gstin: '07ACDPS4412A1Z3', contactPerson: 'Rajesh Sharma', email: 'sharmagrocer@gmail.com', phone: '+91 99100 44332', location: 'Lajpat Nagar II', district: 'South Delhi', totalApplications: 5, totalInstruments: 3, status: 'Under Review' },
  { id: 'APP-05', name: 'Indian Oil Terminal Bijwasan', organization: 'Petroleum Terminal & Depot', gstin: '07AAACI0011R1Z8', contactPerson: 'Siddharth Rao', email: 'bijwasan.depot@indianoil.in', phone: '+91 98111 22110', location: 'Bijwasan Terminal', district: 'South West Delhi', totalApplications: 22, totalInstruments: 34, status: 'Active' },
]

export const initialLmoOfficersList: AdminLmoOfficerStakeholder[] = [
  { id: 'LMO-DEL-042', name: 'L. Mehta (LMO)', employeeId: 'GOV-LM-042', email: 'l.mehta@measuresure.gov.in', phone: '+91 98109 87654', location: 'South Delhi Zone Office', district: 'South Delhi', currentAssignments: 4, completedInspections: 142, status: 'On Field Duty' },
  { id: 'LMO-DEL-019', name: 'R. Iyer (LMO)', employeeId: 'GOV-LM-019', email: 'r.iyer@measuresure.gov.in', phone: '+91 98712 34567', location: 'North Delhi Zone Office', district: 'North Delhi', currentAssignments: 3, completedInspections: 118, status: 'On Field Duty' },
  { id: 'LMO-DEL-088', name: 'S. K. Verma (LMO)', employeeId: 'GOV-LM-088', email: 'sk.verma@measuresure.gov.in', phone: '+91 97111 22334', location: 'North West Zone Office', district: 'North West Delhi', currentAssignments: 5, completedInspections: 165, status: 'Active' },
  { id: 'LMO-DEL-055', name: 'P. Sharma (LMO)', employeeId: 'GOV-LM-055', email: 'p.sharma@measuresure.gov.in', phone: '+91 99100 88776', location: 'Central Zone Office', district: 'Central Delhi', currentAssignments: 2, completedInspections: 94, status: 'Active' },
  { id: 'LMO-DEL-102', name: 'A. K. Rai (LMO)', employeeId: 'GOV-LM-102', email: 'ak.rai@measuresure.gov.in', phone: '+91 98115 55443', location: 'South West Zone Office', district: 'South West Delhi', currentAssignments: 3, completedInspections: 108, status: 'Active' },
]

export const initialGatcOfficersList: AdminGatcOfficerStakeholder[] = [
  { id: 'GATC-DEL-001', name: 'Dr. S. K. Nanda (GATC Officer)', gatcName: 'Narela Regional GATC Testing Laboratory', employeeId: 'GOV-GATC-001', email: 's.nanda@gatc.gov.in', phone: '+91 98100 99881', location: 'Narela Industrial Hub', district: 'North West Delhi', assignedWork: 12, completedTests: 450, status: 'Lab Operational' },
  { id: 'GATC-DEL-002', name: 'Dr. Meenakshi Sundaram', gatcName: 'Okhla Standards & Precision Calibration Centre', employeeId: 'GOV-GATC-002', email: 'm.sundaram@gatc.gov.in', phone: '+91 98188 77665', location: 'Okhla Phase I', district: 'South Delhi', assignedWork: 8, completedTests: 380, status: 'Active' },
  { id: 'GATC-DEL-003', name: 'Er. Rajesh Wadhwa', gatcName: 'Patparganj Metrology Verification Hub', employeeId: 'GOV-GATC-003', email: 'r.wadhwa@gatc.gov.in', phone: '+91 99111 44556', location: 'Patparganj Industrial Area', district: 'East Delhi', assignedWork: 6, completedTests: 290, status: 'Lab Operational' },
]
